/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PQ_VENTANAS;

import PQ_CONTROLADORES.CLS_Controlador;

/**
 *
 * @author ANDY CLARK
 */
public class DGL_UsuarioServicio extends javax.swing.JDialog {

    CLS_Controlador ctrl=new CLS_Controlador();
    /**
     * Creates new form DGL_UsuarioServicio
     */
    public DGL_UsuarioServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ctrl.VisualizarDataEscogidaEnTabla("usuario_nombres,usuario_correo", "v_usuario", TBusuarioServcio, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNususerv = new javax.swing.JPanel();
        LBprovServ = new javax.swing.JLabel();
        TXususerv = new javax.swing.JTextField();
        JSPususerv = new javax.swing.JScrollPane();
        TBusuarioServcio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Traspaso de Solicitante a Servicio.");

        PNususerv.setBackground(new java.awt.Color(255, 255, 255));
        PNususerv.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Usuario Servicio:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        LBprovServ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBprovServ.setText("Usuario:");

        TXususerv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXususervKeyReleased(evt);
            }
        });

        TBusuarioServcio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRES", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBusuarioServcio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBusuarioServcioMouseClicked(evt);
            }
        });
        JSPususerv.setViewportView(TBusuarioServcio);

        javax.swing.GroupLayout PNususervLayout = new javax.swing.GroupLayout(PNususerv);
        PNususerv.setLayout(PNususervLayout);
        PNususervLayout.setHorizontalGroup(
            PNususervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNususervLayout.createSequentialGroup()
                .addComponent(LBprovServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXususerv))
            .addComponent(JSPususerv, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        PNususervLayout.setVerticalGroup(
            PNususervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNususervLayout.createSequentialGroup()
                .addGroup(PNususervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TXususerv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBprovServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSPususerv, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNususerv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNususerv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXususervKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXususervKeyReleased
        // TODO add your handling code here:
        ctrl.BuscarJtable(TXususerv, TBusuarioServcio, 1);
    }//GEN-LAST:event_TXususervKeyReleased

    private void TBusuarioServcioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBusuarioServcioMouseClicked
        // TODO add your handling code here:
        if (ctrl.ValidarRegistroTabla(TBusuarioServcio)) {
            DLG_ORDEN_SERVICIO.txtSolNom.setText(ctrl.ValorTabla(TBusuarioServcio, 0));
            DLG_ORDEN_SERVICIO.txtSolCorreo.setText(ctrl.ValorTabla(TBusuarioServcio, 1));
            this.dispose();
        }
    }//GEN-LAST:event_TBusuarioServcioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DGL_UsuarioServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DGL_UsuarioServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DGL_UsuarioServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DGL_UsuarioServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DGL_UsuarioServicio dialog = new DGL_UsuarioServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSPususerv;
    private javax.swing.JLabel LBprovServ;
    private javax.swing.JPanel PNususerv;
    private javax.swing.JTable TBusuarioServcio;
    private javax.swing.JTextField TXususerv;
    // End of variables declaration//GEN-END:variables
}
