/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PQ_VENTANAS;

import PQ_CONTROLADORES.CLS_Controlador;

/**
 *
 * @author ANDY CLARK
 */
public class DLG_Proveedor_Servicio extends javax.swing.JDialog {

    CLS_Controlador ctrl = new CLS_Controlador();

    /**
     * Creates new form DLG_Proveedor_Servicio
     */
    public DLG_Proveedor_Servicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ctrl.VisualizarEnTabla("proveedor", TBproveedorServcio, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PNLprovServ = new javax.swing.JPanel();
        LBprovServ = new javax.swing.JLabel();
        TXrazonProvServ = new javax.swing.JTextField();
        JSPprovserv = new javax.swing.JScrollPane();
        TBproveedorServcio = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de traspaso de Proveedor.");

        PNLprovServ.setBackground(new java.awt.Color(255, 255, 255));
        PNLprovServ.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Proveedor Servicio.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        LBprovServ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBprovServ.setText("Razón Proveedor:");

        TXrazonProvServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXrazonProvServKeyReleased(evt);
            }
        });

        TBproveedorServcio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "RAZÓN", "REPRESENTANTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBproveedorServcio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBproveedorServcioMouseClicked(evt);
            }
        });
        JSPprovserv.setViewportView(TBproveedorServcio);

        javax.swing.GroupLayout PNLprovServLayout = new javax.swing.GroupLayout(PNLprovServ);
        PNLprovServ.setLayout(PNLprovServLayout);
        PNLprovServLayout.setHorizontalGroup(
            PNLprovServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLprovServLayout.createSequentialGroup()
                .addComponent(LBprovServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXrazonProvServ))
            .addComponent(JSPprovserv, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        PNLprovServLayout.setVerticalGroup(
            PNLprovServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLprovServLayout.createSequentialGroup()
                .addGroup(PNLprovServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TXrazonProvServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBprovServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSPprovserv, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNLprovServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNLprovServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXrazonProvServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXrazonProvServKeyReleased
        // TODO add your handling code here:
        ctrl.BuscarJtable(TXrazonProvServ, TBproveedorServcio, 1);
    }//GEN-LAST:event_TXrazonProvServKeyReleased

    private void TBproveedorServcioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBproveedorServcioMouseClicked
        // TODO add your handling code here:
        if (ctrl.ValidarRegistroTabla(TBproveedorServcio)) {
            DLG_ORDEN_SERVICIO.txtProveedorCod.setText(ctrl.ValorTabla(TBproveedorServcio, 0));
            DLG_ORDEN_SERVICIO.txtProveedorNom.setText(ctrl.ValorTabla(TBproveedorServcio,1));
            this.dispose();
        }

    }//GEN-LAST:event_TBproveedorServcioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLG_Proveedor_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLG_Proveedor_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLG_Proveedor_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLG_Proveedor_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DLG_Proveedor_Servicio dialog = new DLG_Proveedor_Servicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSPprovserv;
    private javax.swing.JLabel LBprovServ;
    private javax.swing.JPanel PNLprovServ;
    private javax.swing.JTable TBproveedorServcio;
    private javax.swing.JTextField TXrazonProvServ;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
