/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PQ_VENTANAS;

import PQ_CONTROLADORES.CLS_Controlador;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
//import org.bolivia.test.DropExcel;

/**
 *
 * @author ANDY
 */
public class DLG_CONSULTA_MOVIMIENTO_FECHAS extends javax.swing.JDialog {

    CLS_Controlador ctrl = new CLS_Controlador();

    /**
     * Creates new form DLG_CONSULTA_MOVIMIENTO_FECHAS
     */
    public DLG_CONSULTA_MOVIMIENTO_FECHAS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ctrl.CerrarVentanaESC(this);
    }

    private void Visualizar(String where) {
        ctrl.VisualizarDataEscogidaEnTabla("movimiento_id_movimiento,detalle_movimiento_id_material,material_descripcion,detalle_movimiento_unidad,detalle_movimiento_cantidad,movimiento_motivo,detalle_movimiento_observacion,almacen_descripcion,proveedor_movimiento,precio_movimiento", "v_movimiento", TBdetalle, where);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBtipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        DT1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        DT2 = new com.toedter.calendar.JDateChooser();
        BTconsultar = new javax.swing.JButton();
        BTexcel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbregistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBdetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimiento por rango de fehas.");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "MOVIMIENTO POR RANGO DE FECHAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Tipo de Movimiento:");

        CBtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STOCK INICIAL", "INGRESO X COMPRA", "SALIDA", "INGRESO X DEVOLUCION", "SALIDA POR DEPURACION" }));

        jLabel2.setText("Desde:");

        DT1.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("Hasta");

        DT2.setDateFormatString("yyyy-MM-dd");

        BTconsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/VER.png"))); // NOI18N
        BTconsultar.setText("Consultar");
        BTconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTconsultarActionPerformed(evt);
            }
        });

        BTexcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/excel.png"))); // NOI18N
        BTexcel.setText("Exportar a Excel");
        BTexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTexcelActionPerformed(evt);
            }
        });

        jLabel4.setText("Se encontraron:");

        TBdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOVIMIENTO", "C. MATERIAL", "D. MATERIAL", "UNIDAD", "CANTIDAD", "OBRA", "OBSERVACION", "ALMACEN", "PROVEEDOR", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBdetalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TBdetalle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbregistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTexcel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DT1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DT2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTconsultar)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(DT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTconsultar)
                    .addComponent(jLabel3)
                    .addComponent(CBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lbregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BTexcel))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTconsultarActionPerformed
        // TODO add your handling code here:
        Consultar();
    }//GEN-LAST:event_BTconsultarActionPerformed

    private void BTexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexcelActionPerformed
        // TODO add your handling code here:
        if (TBdetalle.getRowCount() == 0) {
            ctrl.mensaje.MensajeAlerta("No hay ningun elemento para exportar.");
        } else {
            JFileChooser seleccionar = new JFileChooser();
            File archivo;
            if (seleccionar.showDialog(null, "Exportar Excel") == JFileChooser.APPROVE_OPTION) {
                archivo = seleccionar.getSelectedFile();
                int cantFila = TBdetalle.getRowCount();
                int cantColumna = TBdetalle.getColumnCount();
                Workbook wb;
                wb = new XSSFWorkbook();
                Sheet hoja = wb.createSheet("  ");

                try {
                    for (int i = -1; i < cantFila; i++) {
                        Row fila = hoja.createRow(i + 1);
                        for (int j = 0; j < cantColumna; j++) {
                            Cell celda = fila.createCell(j);
                            if (i == -1) {
                                celda.setCellValue(String.valueOf(TBdetalle.getColumnName(j)));
                            } else {
                                celda.setCellValue(String.valueOf(TBdetalle.getValueAt(i, j)));
                            }
                            wb.write(new FileOutputStream(archivo + ".xlsx"));
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Exportacion exitosa");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
                }

            } else {

            }
        }
    }//GEN-LAST:event_BTexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLG_CONSULTA_MOVIMIENTO_FECHAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLG_CONSULTA_MOVIMIENTO_FECHAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLG_CONSULTA_MOVIMIENTO_FECHAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLG_CONSULTA_MOVIMIENTO_FECHAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DLG_CONSULTA_MOVIMIENTO_FECHAS dialog = new DLG_CONSULTA_MOVIMIENTO_FECHAS(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTconsultar;
    private javax.swing.JButton BTexcel;
    private javax.swing.JComboBox<String> CBtipo;
    private com.toedter.calendar.JDateChooser DT1;
    private com.toedter.calendar.JDateChooser DT2;
    public static javax.swing.JTable TBdetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbregistros;
    // End of variables declaration//GEN-END:variables

    private void Consultar() {
        if (DT1.getDate() == null) {
            ctrl.mensaje.MensajeAlerta("Ud. no ingresó la fecha DESDE.");
        } else if (DT2.getDate() == null) {
            ctrl.mensaje.MensajeAlerta("Ud. no ingresó la fecha HASTA.");
        } else {
            Visualizar("where (movimiento_fecha BETWEEN '" + ctrl.DevolverFechaJDateChooser(DT1) + "' AND '" + ctrl.DevolverFechaJDateChooser(DT2) + "')and movimiento_tipo_movimiento='" + CBtipo.getSelectedItem().toString().trim() + "' order by movimiento_id_movimiento");
        }
    }
}
