/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PQ_VENTANAS;

import PQ_CONTROLADORES.CLS_Controlador;

/**
 *
 * @author Andy Figueroa
 */
public class DLG_DETALLE_ORDEN_POR_EVALUACION extends javax.swing.JDialog {

    CLS_Controlador ctrl=new CLS_Controlador();
    /**
     * Creates new form DLG_DETALLE_ORDEN_POR_EVALUACION
     */
    public DLG_DETALLE_ORDEN_POR_EVALUACION(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ctrl.VisualizarEnTabla("v_adicion_orden", TBAdherir, "where detalle_requerimiento_id_requerimiento='"+IFRM_ORDEN_COMPRA.TXrequerimiento.getText().trim()+"'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBAdherir = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA DE ADICIÓN DE MATERIALES DE REQUERIMIENTO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "MATERIALE EVALUADOS A ADHERIR A ORDEN DE COMPRA:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        TBAdherir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.Material", "Material", "C.Requerimiento", "Cantidad", "Unidad", "P.Unitario", "P.total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBAdherir.getTableHeader().setReorderingAllowed(false);
        TBAdherir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBAdherirKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TBAdherir);
        if (TBAdherir.getColumnModel().getColumnCount() > 0) {
            TBAdherir.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/DETALLAR.png"))); // NOI18N
        jButton1.setText("Detallar Todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/ADICIONAR.png"))); // NOI18N
        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBAdherirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBAdherirKeyReleased
        // TODO add your handling code here:
        TBAdherir.setValueAt((Double.parseDouble(ctrl.ValorTabla(TBAdherir, 3))*Double.parseDouble(ctrl.ValorTabla(TBAdherir, 5))), ctrl.PosicionTabla(TBAdherir), 6);
    }//GEN-LAST:event_TBAdherirKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Detallar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        IFRM_ORDEN_COMPRA.BTcalcular.doClick();
        IFRM_ORDEN_COMPRA.CH_por_requerimiento.setSelected(false);
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adicionar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLG_DETALLE_ORDEN_POR_EVALUACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLG_DETALLE_ORDEN_POR_EVALUACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLG_DETALLE_ORDEN_POR_EVALUACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLG_DETALLE_ORDEN_POR_EVALUACION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DLG_DETALLE_ORDEN_POR_EVALUACION dialog = new DLG_DETALLE_ORDEN_POR_EVALUACION(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBAdherir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Detallar() 
    {
        try 
        {
            for(int i=0;i<TBAdherir.getRowCount();i++)        
            {
                if(ctrl.ValorTabla(TBAdherir, 5).toString().trim().length()==0 || ctrl.ValorTabla(TBAdherir, 6).toString().trim().length()==0)
                {
                    ctrl.mensaje.MensajeAlerta("Valores vacios");                    
                }
                else
                {
                    String orden=IFRM_ORDEN_COMPRA.TXorden.getText().trim();
                    ctrl.GrabarData("detalle_orden", "id_material,id_orden,cantidad,p_unitario,p_total,asiganado,unidad", "'"+TBAdherir.getValueAt(i, 0).toString().trim()+"'"
                            + ",'"+orden+"','"+TBAdherir.getValueAt(i, 3).toString().trim()+"','"+TBAdherir.getValueAt(i, 5).toString().trim()+"','"+TBAdherir.getValueAt(i, 6).toString().trim()+"',2,'"+TBAdherir.getValueAt(i, 4).toString().trim()+"'");
                }
            }            
        } catch (NullPointerException e)
        {
            ctrl.mensaje.MensajeAlerta("Valores nulos:\n"+e.getMessage());
        }
        
    }
    private void Adicionar()
    {
        if(TBAdherir.getRowCount()==0)
        {
            ctrl.mensaje.MensajeAlerta("No hay nada que adherir");
        }
        else if(TBAdherir.getSelectedRow()==-1)
        {
            ctrl.mensaje.MensajeAlerta("Ud. no seleccionó ningún item.");
        }
        else if(TBAdherir.getSelectedRowCount()>1)
        {
            ctrl.mensaje.MensajeAlerta("Seleccione solo un item.");
        }
        else
        {
            try 
            {
                if(ctrl.ValorTabla(TBAdherir, 5).toString().trim().length()==0 || ctrl.ValorTabla(TBAdherir, 6).toString().trim().length()==0)
                {

                }
                else
                {
                    String orden=IFRM_ORDEN_COMPRA.TXorden.getText().trim();
                    ctrl.GrabarData("detalle_orden", "id_material,id_orden,cantidad,p_unitario,p_total,asiganado,unidad", "'"+ctrl.ValorTabla(TBAdherir, 0).toString().trim()+"'"
                         + ",'"+orden+"','"+ctrl.ValorTabla(TBAdherir, 3).toString().trim()+"','"+ctrl.ValorTabla(TBAdherir, 5).toString().trim()+"','"+ctrl.ValorTabla(TBAdherir, 6).toString().trim()+"',2,'"+ctrl.ValorTabla(TBAdherir, 4).toString().trim()+"'");
                }           
            } catch (NullPointerException e)
            {
                ctrl.mensaje.MensajeAlerta("Valores nulos:\n"+e.getMessage());
            }  
        }
                  
    }
}
