/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PQ_VENTANAS;

import PQ_CONTROLADORES.CLS_Controlador;

/**
 *
 * @author ANDY CLARK
 */
public class IFRM_OrdenServicio extends javax.swing.JInternalFrame {

    CLS_Controlador ctrl=new CLS_Controlador();
    /**
     * Creates new form IFRM_OrdenServicio
     */
    public IFRM_OrdenServicio() {
        initComponents();
        Cancelar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        BTnuevo = new javax.swing.JButton();
        BTcancelar = new javax.swing.JButton();
        BTsalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBordenservicio = new javax.swing.JTable();

        jPopupMenu1.setBackground(new java.awt.Color(0, 102, 204));
        jPopupMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setText("Detallar Servicio");
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Ventana de Generación de Orden de Servicio.");
        setToolTipText(this.getTitle());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        BTnuevo.setBackground(new java.awt.Color(255, 255, 255));
        BTnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/ADICIONAR.png"))); // NOI18N
        BTnuevo.setText("Nuevo");
        BTnuevo.setFocusable(false);
        BTnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(BTnuevo);

        BTcancelar.setBackground(new java.awt.Color(255, 255, 255));
        BTcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/CANCELAR.png"))); // NOI18N
        BTcancelar.setText("Cancelar");
        BTcancelar.setFocusable(false);
        BTcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BTcancelar);

        BTsalir.setBackground(new java.awt.Color(255, 255, 255));
        BTsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PQ_IMAGENES/SALIR.png"))); // NOI18N
        BTsalir.setText("Salir");
        BTsalir.setFocusable(false);
        BTsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(BTsalir);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Lista de Ordenes Generadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TBordenservicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.SERVICIO", "F.EMISIÓN", "F.PAGO", "MODENA", "PROVEEDOR", "RUC", "C.COSTOS", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBordenservicio.setComponentPopupMenu(jPopupMenu1);
        TBordenservicio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TBordenservicio);
        if (TBordenservicio.getColumnModel().getColumnCount() > 0) {
            TBordenservicio.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTnuevoActionPerformed
        // TODO add your handling code here:
        DLG_ORDEN_SERVICIO dlg=new DLG_ORDEN_SERVICIO(null,true);
        dlg.setVisible(true);
    }//GEN-LAST:event_BTnuevoActionPerformed

    private void BTsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcancelar;
    private javax.swing.JButton BTnuevo;
    private javax.swing.JButton BTsalir;
    public static javax.swing.JTable TBordenservicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void Cancelar() {
        ctrl.VisualizarDataEscogidaEnTabla("idordenservicio,fecha_emision,forma_pago,moneda,razon,ruc,centro_costos,estado", "v_ordenservicio", TBordenservicio, "where estado='EMITIDO' or estado='DETALLADO'");
    }
}
